//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekCV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YemekCVEntities : DbContext
    {
        public YemekCVEntities()
            : base("name=YemekCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLadres> TBLadres { get; set; }
        public virtual DbSet<TBLcalismalarim> TBLcalismalarim { get; set; }
        public virtual DbSet<TBLhakkimda> TBLhakkimda { get; set; }
        public virtual DbSet<TBLiletisim> TBLiletisim { get; set; }
        public virtual DbSet<TBLyetenekler> TBLyetenekler { get; set; }
    }
}
