//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekCV
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLhakkimda
    {
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string Egitim { get; set; }
        public string IsDeneyimi { get; set; }
        public string Unvan { get; set; }
    }
}
